### ISSUE TITLE
'clr' has no attribute 'AddReferenceByName'

### ISSUE THREAD

**Issue by Cyril-Pop** [DynamoDS/DSIronPython3#1]
## Dynamo version

2.17 SandBox

## Operating system

Win 11

## What did you expect to see?

No Error, printing some object

result in other IDE
![image](https://user-images.githubusercontent.com/53660624/229310681-b193dc00-59c9-44e1-9368-ac26010cf7a0.png)

## What did you see instead?

Error
Messages: AttributeError : module 'clr' has no attribute 'AddReferenceByName' ['  File "<string>", line 21, in <module>\n']
State: Warning

![image](https://user-images.githubusercontent.com/53660624/229310820-aedb10bc-ee97-4deb-8af8-aaa937327cca.png)

**Comment by Cyril-Pop** [comment]
after re-testing the error disappeared, I have the impression the ipy3 engine has switched internally to CPython3 engine

**Comment by mjkkirschner** [comment]
thanks @Cyril-Pop - if we can reproduce the switch (or you can) - I'll open a task to fix it.
