### ISSUE TITLE
COM Objects are not cast/recognized in the correct Interface

### ISSUE THREAD

**Issue by Cyril-Pop** [DynamoDS/DSIronPython3#3]
Hi,

## Dynamo version

Dynamo Revit 2.19 

## Operating system

Win 10

## What did you expect to see?

COM objects are cast/recognized in the correct Interface (like Ipy2)

![com naviswkorks Ipy2](https://github.com/DynamoDS/DSIronPython3/assets/53660624/2282591f-b91f-452c-9763-8c9a3efbdbf6)

## What did you see instead?

COM objects which are not cast/recognized in the correct Interface (like PythonNet), same problem with Excel interrop or Autocad Interrop

![com naviswkorks Ipy3](https://github.com/DynamoDS/DSIronPython3/assets/53660624/bf18df40-945c-483b-8143-64c0cf39a1c4)

## code to reproduce 

```
import clr
import sys
import System
navis_path = r'C:\Program Files\Autodesk\Navisworks Manage 2022'
filemodel = IN[0] 
sys.path.append(navis_path)

#?clr.AddReference('Autodesk.Navisworks.Api')
clr.AddReference('Autodesk.Navisworks.Automation')
clr.AddReference('Autodesk.Navisworks.Controls')
clr.AddReference('Autodesk.Navisworks.Resolver')
clr.AddReference('Autodesk.Navisworks.ComApi')
clr.AddReference('Autodesk.Navisworks.Interop.ComApi')
clr.AddReference('Autodesk.Navisworks.Interop.ComApiAutomation')

import Autodesk.Navisworks.Api as API
import Autodesk.Navisworks.Api.ComApi as COMAPI
import Autodesk.Navisworks.Api.Interop.ComApi as ICOMAPI
import Autodesk.Navisworks.Api.Interop.ComApiAutomation as ICOMAPI_AUT
from Autodesk.Navisworks.Api import *
from Autodesk.Navisworks.Api.Automation import *
from Autodesk.Navisworks.Api.Controls import *
#from Autodesk.Navisworks.Api.ApplicationParts import *
from System.Collections.Generic import List
import Autodesk

app = API.Controls.ApplicationControl.ApplicationType.SingleDocument
navis_doc = ICOMAPI_AUT.DocumentClass()

file_path_nwc = IN[0]
navis_doc.OpenFile(file_path_nwc)
navis_doc.Visible = True
navis_doc.StayOpen()
state = navis_doc.State()

all_childs = state.CurrentPartition.Children()
all_plugins = state.Plugins()

OUT = state, navis_doc
```

**Comment by mjkkirschner** [comment]
@Cyril-Pop have you also reported this to the IronPython3 project?

**Comment by Cyril-Pop** [comment]
Hi @mjkkirschner 
I did not report the bug to IronPython Team because it works well with IronPython3 alone

Test in video with IronPython3 folder content

![test Navis COM](https://github.com/DynamoDS/DSIronPython3/assets/53660624/eabc8429-ef06-4f9f-8afe-ec142f9040ef)

**Comment by mjkkirschner** [comment]
was this also the case with IronPython 3.4.0?

**Comment by Cyril-Pop** [comment]
yes, I just tested it now it also works with IronPython3.4.0

**Comment by Cyril-Pop** [comment]
This is very strange because it is seem an error specific to PythonNet

**Comment by mjkkirschner** [comment]
perhaps, the engine is not actually being set to IronPython in some edge case.

**Comment by Cyril-Pop** [comment]
maybe this would explain why this error doesn't occur with IPy2

![image](https://github.com/DynamoDS/DSIronPython3/assets/53660624/f1ff4a7b-c64d-46b4-8f19-f80f4513491f)

**Comment by Cyril-Pop** [comment]
Hi @mjkkirschner 

At first glance the problem is fixed now

-  **Before with Ipy3.4**

![image](https://github.com/DynamoDS/DSIronPython3/assets/53660624/fdfa1217-f82d-49d6-9171-4cf5665d107c)

- **After with Ipy3.4.1 on Net7.0**

![image](https://github.com/DynamoDS/DSIronPython3/assets/53660624/165ec157-71ac-4c20-8a35-4aa3f0967c49)

**Comment by Cyril-Pop** [comment]
works well with Excel Interop too.

I will test later with Navisworks because the current dlls (api) target NetFramework 4.x and therefore cannot be loaded in Net 6+ core

thanks
