### ISSUE TITLE
Assemblies conflicts between Ipy2 and Ipy3

### ISSUE THREAD

**Issue by Cyril-Pop** [DynamoDS/DSIronPython3#5]
Dynamo version
---
DynamoCoreRuntime_3.0.0.6646

Operating system
---
Win 11

What did you expect to see?
---
No Error running IronPython3 engine

What did you see instead?
---

When IronPython2 engine is installed too, IronPython3 load **Ipy2** assemblies instead **Ipy3** assemblies

![image](https://github.com/DynamoDS/DSIronPython3/assets/53660624/504d3cfb-0b1b-4442-9afb-515820cfb0a7)

steps to reproduce
---

https://github.com/DynamoDS/DSIronPython3/assets/53660624/c21b35e1-be7e-4cc1-9204-0df01c9e163b

**Comment by mjkkirschner** [comment]
this should be resolved with the latest version of DSIronPython2.x
